# Generated by Django 3.0.2 on 2020-01-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progess',
            new_name='Progress',
        ),
    ]
